CRITICAL - 2024-04-03 00:22:48 --> CodeIgniter\Router\Exceptions\RouterException: The namespace delimiter is a backslash (\), not a slash (/). Route handler: "\App\Controllers\login/login/login::index"
in SYSTEMPATH\Router\Router.php on line 495.
 1 SYSTEMPATH\Router\Router.php(495): CodeIgniter\Router\Exceptions\RouterException::forInvalidControllerName('\\App\\Controllers\\login/login/login::index')
 2 SYSTEMPATH\Router\Router.php(202): CodeIgniter\Router\Router->checkRoutes('/')
 3 SYSTEMPATH\CodeIgniter.php(825): CodeIgniter\Router\Router->handle('/')
 4 SYSTEMPATH\CodeIgniter.php(450): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 00:22:56 --> CodeIgniter\Router\Exceptions\RouterException: The namespace delimiter is a backslash (\), not a slash (/). Route handler: "\App\Controllers\login/login/login::index"
in SYSTEMPATH\Router\Router.php on line 495.
 1 SYSTEMPATH\Router\Router.php(495): CodeIgniter\Router\Exceptions\RouterException::forInvalidControllerName('\\App\\Controllers\\login/login/login::index')
 2 SYSTEMPATH\Router\Router.php(202): CodeIgniter\Router\Router->checkRoutes('/')
 3 SYSTEMPATH\CodeIgniter.php(825): CodeIgniter\Router\Router->handle('/')
 4 SYSTEMPATH\CodeIgniter.php(450): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 00:23:01 --> CodeIgniter\Router\Exceptions\RouterException: The namespace delimiter is a backslash (\), not a slash (/). Route handler: "\App\Controllers\login/login::index"
in SYSTEMPATH\Router\Router.php on line 495.
 1 SYSTEMPATH\Router\Router.php(495): CodeIgniter\Router\Exceptions\RouterException::forInvalidControllerName('\\App\\Controllers\\login/login::index')
 2 SYSTEMPATH\Router\Router.php(202): CodeIgniter\Router\Router->checkRoutes('/')
 3 SYSTEMPATH\CodeIgniter.php(825): CodeIgniter\Router\Router->handle('/')
 4 SYSTEMPATH\CodeIgniter.php(450): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 00:33:32 --> CodeIgniter\Router\Exceptions\RouterException: The namespace delimiter is a backslash (\), not a slash (/). Route handler: "\App\Controllers\login/login::index"
in SYSTEMPATH\Router\Router.php on line 495.
 1 SYSTEMPATH\Router\Router.php(495): CodeIgniter\Router\Exceptions\RouterException::forInvalidControllerName('\\App\\Controllers\\login/login::index')
 2 SYSTEMPATH\Router\Router.php(202): CodeIgniter\Router\Router->checkRoutes('/')
 3 SYSTEMPATH\CodeIgniter.php(825): CodeIgniter\Router\Router->handle('/')
 4 SYSTEMPATH\CodeIgniter.php(450): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 00:33:51 --> CodeIgniter\Router\Exceptions\RouterException: The namespace delimiter is a backslash (\), not a slash (/). Route handler: "\App\Controllers\login/login/Login::index"
in SYSTEMPATH\Router\Router.php on line 495.
 1 SYSTEMPATH\Router\Router.php(495): CodeIgniter\Router\Exceptions\RouterException::forInvalidControllerName('\\App\\Controllers\\login/login/Login::index')
 2 SYSTEMPATH\Router\Router.php(202): CodeIgniter\Router\Router->checkRoutes('/')
 3 SYSTEMPATH\CodeIgniter.php(825): CodeIgniter\Router\Router->handle('/')
 4 SYSTEMPATH\CodeIgniter.php(450): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 01:23:24 --> Error: Call to a member function get_data_user() on null
in APPPATH\Controllers\login\login.php on line 34.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 01:25:21 --> Error: Call to a member function get_data_user() on null
in APPPATH\Controllers\login\login.php on line 34.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 01:30:28 --> Error: Call to a member function get_data_user() on null
in APPPATH\Controllers\login\login.php on line 34.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 01:38:46 --> TypeError: Dotenv\Dotenv::create(): Argument #1 ($repository) must be of type Dotenv\Repository\RepositoryInterface, string given, called in C:\laragon\www\App_transports\app\Controllers\login\login.php on line 28
in VENDORPATH\vlucas\phpdotenv\src\Dotenv.php on line 83.
 1 APPPATH\Controllers\login\login.php(28): Dotenv\Dotenv::create('C:\\laragon\\www\\App_transports\\', '.env')
 2 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->index()
 3 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 01:38:49 --> TypeError: Dotenv\Dotenv::create(): Argument #1 ($repository) must be of type Dotenv\Repository\RepositoryInterface, string given, called in C:\laragon\www\App_transports\app\Controllers\login\login.php on line 28
in VENDORPATH\vlucas\phpdotenv\src\Dotenv.php on line 83.
 1 APPPATH\Controllers\login\login.php(28): Dotenv\Dotenv::create('C:\\laragon\\www\\App_transports\\', '.env')
 2 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->index()
 3 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 01:39:02 --> TypeError: Dotenv\Dotenv::create(): Argument #1 ($repository) must be of type Dotenv\Repository\RepositoryInterface, string given, called in C:\laragon\www\App_transports\app\Controllers\login\login.php on line 28
in VENDORPATH\vlucas\phpdotenv\src\Dotenv.php on line 83.
 1 APPPATH\Controllers\login\login.php(28): Dotenv\Dotenv::create('C:\\laragon\\www\\App_transports\\', '.env')
 2 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->index()
 3 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 01:39:46 --> TypeError: Dotenv\Dotenv::create(): Argument #1 ($repository) must be of type Dotenv\Repository\RepositoryInterface, string given, called in C:\laragon\www\App_transports\app\Controllers\login\login.php on line 28
in VENDORPATH\vlucas\phpdotenv\src\Dotenv.php on line 83.
 1 APPPATH\Controllers\login\login.php(28): Dotenv\Dotenv::create('C:\\laragon\\www\\App_transports\\', '.env')
 2 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->index()
 3 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 01:39:50 --> TypeError: Dotenv\Dotenv::create(): Argument #1 ($repository) must be of type Dotenv\Repository\RepositoryInterface, string given, called in C:\laragon\www\App_transports\app\Controllers\login\login.php on line 28
in VENDORPATH\vlucas\phpdotenv\src\Dotenv.php on line 83.
 1 APPPATH\Controllers\login\login.php(28): Dotenv\Dotenv::create('C:\\laragon\\www\\App_transports\\', '.env')
 2 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->index()
 3 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 01:40:22 --> TypeError: Dotenv\Dotenv::create(): Argument #1 ($repository) must be of type Dotenv\Repository\RepositoryInterface, string given, called in C:\laragon\www\App_transports\app\Controllers\login\login.php on line 28
in VENDORPATH\vlucas\phpdotenv\src\Dotenv.php on line 83.
 1 APPPATH\Controllers\login\login.php(28): Dotenv\Dotenv::create('C:\\laragon\\www\\App_transports\\', '.env')
 2 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->index()
 3 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 01:40:33 --> TypeError: Dotenv\Dotenv::create(): Argument #1 ($repository) must be of type Dotenv\Repository\RepositoryInterface, string given, called in C:\laragon\www\App_transports\app\Controllers\login\login.php on line 28
in VENDORPATH\vlucas\phpdotenv\src\Dotenv.php on line 83.
 1 APPPATH\Controllers\login\login.php(28): Dotenv\Dotenv::create('C:\\laragon\\www\\App_transports\\', '.env')
 2 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->index()
 3 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 01:40:47 --> TypeError: Dotenv\Dotenv::create(): Argument #1 ($repository) must be of type Dotenv\Repository\RepositoryInterface, string given, called in C:\laragon\www\App_transports\app\Controllers\login\login.php on line 28
in VENDORPATH\vlucas\phpdotenv\src\Dotenv.php on line 83.
 1 APPPATH\Controllers\login\login.php(28): Dotenv\Dotenv::create('C:\\laragon\\www\\App_transports\\', '.env')
 2 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->index()
 3 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 01:41:43 --> TypeError: Dotenv\Dotenv::create(): Argument #1 ($repository) must be of type Dotenv\Repository\RepositoryInterface, string given, called in C:\laragon\www\App_transports\app\Controllers\login\login.php on line 28
in VENDORPATH\vlucas\phpdotenv\src\Dotenv.php on line 83.
 1 APPPATH\Controllers\login\login.php(28): Dotenv\Dotenv::create('C:\\laragon\\www\\App_transports\\', '.env')
 2 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->index()
 3 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 01:41:55 --> TypeError: Dotenv\Dotenv::create(): Argument #1 ($repository) must be of type Dotenv\Repository\RepositoryInterface, string given, called in C:\laragon\www\App_transports\app\Controllers\login\login.php on line 28
in VENDORPATH\vlucas\phpdotenv\src\Dotenv.php on line 83.
 1 APPPATH\Controllers\login\login.php(28): Dotenv\Dotenv::create('C:\\laragon\\www\\App_transports\\', '.env')
 2 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->index()
 3 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 01:43:30 --> TypeError: Dotenv\Dotenv::create(): Argument #1 ($repository) must be of type Dotenv\Repository\RepositoryInterface, string given, called in C:\laragon\www\App_transports\app\Controllers\login\login.php on line 28
in VENDORPATH\vlucas\phpdotenv\src\Dotenv.php on line 83.
 1 APPPATH\Controllers\login\login.php(28): Dotenv\Dotenv::create('C:\\laragon\\www\\App_transports\\', '.env')
 2 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->index()
 3 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 01:43:32 --> TypeError: Dotenv\Dotenv::create(): Argument #1 ($repository) must be of type Dotenv\Repository\RepositoryInterface, string given, called in C:\laragon\www\App_transports\app\Controllers\login\login.php on line 28
in VENDORPATH\vlucas\phpdotenv\src\Dotenv.php on line 83.
 1 APPPATH\Controllers\login\login.php(28): Dotenv\Dotenv::create('C:\\laragon\\www\\App_transports\\', '.env')
 2 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->index()
 3 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 01:44:03 --> Error: Call to a member function get_data_user() on null
in APPPATH\Controllers\login\login.php on line 37.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:01:17 --> Error: Call to a member function getEnv() on null
in APPPATH\Controllers\login\login.php on line 30.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->index()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:03:58 --> Error: Call to a member function getEnv() on null
in APPPATH\Controllers\login\login.php on line 30.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->index()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:05:50 --> Error: Call to a member function getEnv() on null
in APPPATH\Controllers\login\login.php on line 30.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->index()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:05:53 --> Error: Call to a member function getEnv() on null
in APPPATH\Controllers\login\login.php on line 30.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->index()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:06:09 --> Error: Call to a member function getEnv() on null
in APPPATH\Controllers\login\login.php on line 30.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->index()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:06:23 --> Error: Call to a member function getEnv() on null
in APPPATH\Controllers\login\login.php on line 30.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->index()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:08:06 --> Exception: No se pudo cargar el servicio Environment
in APPPATH\Controllers\login\login.php on line 32.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->index()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:08:35 --> Exception: No se pudo cargar el servicio Environment
in APPPATH\Controllers\login\login.php on line 32.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->index()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:13:13 --> Error: Call to a member function get_data_user() on null
in APPPATH\Controllers\login\login.php on line 37.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:13:48 --> Error: Call to a member function get_data_user() on null
in APPPATH\Controllers\login\login.php on line 37.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:14:55 --> Error: Call to a member function get_data_user() on null
in APPPATH\Controllers\login\login.php on line 37.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:15:09 --> Error: Call to a member function get_data_user() on null
in APPPATH\Controllers\login\login.php on line 37.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:15:30 --> Error: Class "App\Models\loginModel" not found
in SYSTEMPATH\Config\Factories.php on line 218.
 1 SYSTEMPATH\Config\Factories.php(168): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\loginModel', [...])
 2 SYSTEMPATH\Common.php(813): CodeIgniter\Config\Factories::__callStatic('models', [...])
 3 APPPATH\Controllers\login\login.php(18): model('App/Models/login\\loginModel')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\login\login->__construct()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:21:00 --> Error: Class "App\Models\loginModel" not found
in SYSTEMPATH\Config\Factories.php on line 218.
 1 SYSTEMPATH\Config\Factories.php(168): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\loginModel', [...])
 2 SYSTEMPATH\Common.php(813): CodeIgniter\Config\Factories::__callStatic('models', [...])
 3 APPPATH\Controllers\login\login.php(18): model('App/Models/login\\loginModel')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\login\login->__construct()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:21:40 --> Error: Class "App\Models\loginModel" not found
in SYSTEMPATH\Config\Factories.php on line 218.
 1 SYSTEMPATH\Config\Factories.php(168): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\loginModel', [...])
 2 SYSTEMPATH\Common.php(813): CodeIgniter\Config\Factories::__callStatic('models', [...])
 3 APPPATH\Controllers\login\login.php(18): model('App/Models/login\\loginModel')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\login\login->__construct()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:21:50 --> Error: Class "App\Models\loginModel" not found
in SYSTEMPATH\Config\Factories.php on line 218.
 1 SYSTEMPATH\Config\Factories.php(168): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\loginModel', [...])
 2 SYSTEMPATH\Common.php(813): CodeIgniter\Config\Factories::__callStatic('models', [...])
 3 APPPATH\Controllers\login\login.php(18): model('App/Models/login\\loginModel')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\login\login->__construct()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:22:01 --> Error: Class "App\Models\loginModel" not found
in SYSTEMPATH\Config\Factories.php on line 218.
 1 SYSTEMPATH\Config\Factories.php(168): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\loginModel', [...])
 2 SYSTEMPATH\Common.php(813): CodeIgniter\Config\Factories::__callStatic('models', [...])
 3 APPPATH\Controllers\login\login.php(18): model('App/Models/login\\loginModel')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\login\login->__construct()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:22:03 --> Error: Class "App\Models\loginModel" not found
in SYSTEMPATH\Config\Factories.php on line 218.
 1 SYSTEMPATH\Config\Factories.php(168): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\loginModel', [...])
 2 SYSTEMPATH\Common.php(813): CodeIgniter\Config\Factories::__callStatic('models', [...])
 3 APPPATH\Controllers\login\login.php(18): model('App/Models/login\\loginModel')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\login\login->__construct()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:22:06 --> Error: Class "App\Models\loginModel" not found
in SYSTEMPATH\Config\Factories.php on line 218.
 1 SYSTEMPATH\Config\Factories.php(168): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\loginModel', [...])
 2 SYSTEMPATH\Common.php(813): CodeIgniter\Config\Factories::__callStatic('models', [...])
 3 APPPATH\Controllers\login\login.php(18): model('App/Models/login\\loginModel')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\login\login->__construct()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:22:11 --> Error: Class "App\Models\loginModel" not found
in SYSTEMPATH\Config\Factories.php on line 218.
 1 SYSTEMPATH\Config\Factories.php(168): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\loginModel', [...])
 2 SYSTEMPATH\Common.php(813): CodeIgniter\Config\Factories::__callStatic('models', [...])
 3 APPPATH\Controllers\login\login.php(18): model('App/Models/login\\loginModel')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\login\login->__construct()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:22:15 --> Error: Class "App\Models\loginModel" not found
in SYSTEMPATH\Config\Factories.php on line 218.
 1 SYSTEMPATH\Config\Factories.php(168): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\loginModel', [...])
 2 SYSTEMPATH\Common.php(813): CodeIgniter\Config\Factories::__callStatic('models', [...])
 3 APPPATH\Controllers\login\login.php(18): model('App/Models/login\\loginModel')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\login\login->__construct()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:22:25 --> Error: Class "App\Models\loginModel" not found
in SYSTEMPATH\Config\Factories.php on line 218.
 1 SYSTEMPATH\Config\Factories.php(168): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\loginModel', [...])
 2 SYSTEMPATH\Common.php(813): CodeIgniter\Config\Factories::__callStatic('models', [...])
 3 APPPATH\Controllers\login\login.php(18): model('App/Models/login\\loginModel')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\login\login->__construct()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:22:49 --> Error: Class "App\Models\loginModel" not found
in SYSTEMPATH\Config\Factories.php on line 218.
 1 SYSTEMPATH\Config\Factories.php(168): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\loginModel', [...])
 2 SYSTEMPATH\Common.php(813): CodeIgniter\Config\Factories::__callStatic('models', [...])
 3 APPPATH\Controllers\login\login.php(18): model('App/Models/login\\loginModel')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\login\login->__construct()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:22:52 --> Error: Class "App\Models\loginModel" not found
in SYSTEMPATH\Config\Factories.php on line 218.
 1 SYSTEMPATH\Config\Factories.php(168): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\loginModel', [...])
 2 SYSTEMPATH\Common.php(813): CodeIgniter\Config\Factories::__callStatic('models', [...])
 3 APPPATH\Controllers\login\login.php(18): model('App/Models/login\\loginModel')
 4 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\login\login->__construct()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:23:10 --> Error: Call to a member function get_data_user() on null
in APPPATH\Controllers\login\login.php on line 38.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:24:16 --> Error: Call to a member function get_data_user() on null
in APPPATH\Controllers\login\login.php on line 42.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:29:30 --> Error: Call to a member function get_data_user() on null
in APPPATH\Controllers\login\login.php on line 42.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:31:37 --> Error: Call to a member function get_data_user() on null
in APPPATH\Controllers\login\login.php on line 46.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:32:49 --> Error: Call to a member function get_data_user() on null
in APPPATH\Controllers\login\login.php on line 46.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:33:41 --> Error: Call to a member function get_data_user() on null
in APPPATH\Controllers\login\login.php on line 43.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:35:28 --> CodeIgniter\Database\Exceptions\DatabaseException: You must set the database table to be used with your query.
in SYSTEMPATH\Database\BaseConnection.php on line 884.
 1 SYSTEMPATH\Model.php(663): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH\Model.php(869): CodeIgniter\Model->builder()
 3 APPPATH\Models\login\loginModel.php(10): CodeIgniter\Model->__call('where', [...])
 4 APPPATH\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('asas')
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:35:44 --> CodeIgniter\Database\Exceptions\DatabaseException: You must set the database table to be used with your query.
in SYSTEMPATH\Database\BaseConnection.php on line 884.
 1 SYSTEMPATH\Model.php(663): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH\Model.php(869): CodeIgniter\Model->builder()
 3 APPPATH\Models\login\loginModel.php(10): CodeIgniter\Model->__call('where', [...])
 4 APPPATH\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('asas')
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:36:09 --> CodeIgniter\Database\Exceptions\DatabaseException: You must set the database table to be used with your query.
in SYSTEMPATH\Database\BaseConnection.php on line 884.
 1 SYSTEMPATH\Model.php(663): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH\Model.php(869): CodeIgniter\Model->builder()
 3 APPPATH\Models\login\loginModel.php(10): CodeIgniter\Model->__call('where', [...])
 4 APPPATH\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('asas')
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:36:23 --> CodeIgniter\Database\Exceptions\DatabaseException: You must set the database table to be used with your query.
in SYSTEMPATH\Database\BaseConnection.php on line 884.
 1 SYSTEMPATH\Model.php(663): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH\Model.php(869): CodeIgniter\Model->builder()
 3 APPPATH\Models\login\loginModel.php(10): CodeIgniter\Model->__call('where', [...])
 4 APPPATH\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('asas')
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:37:25 --> CodeIgniter\Database\Exceptions\DatabaseException: You must set the database table to be used with your query.
in SYSTEMPATH\Database\BaseConnection.php on line 884.
 1 SYSTEMPATH\Model.php(663): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH\Model.php(869): CodeIgniter\Model->builder()
 3 APPPATH\Models\login\loginModel.php(10): CodeIgniter\Model->__call('where', [...])
 4 APPPATH\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('fdfdf')
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:38:36 --> CodeIgniter\Database\Exceptions\DatabaseException: You must set the database table to be used with your query.
in SYSTEMPATH\Database\BaseConnection.php on line 884.
 1 SYSTEMPATH\Model.php(663): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH\Model.php(869): CodeIgniter\Model->builder()
 3 APPPATH\Models\login\loginModel.php(11): CodeIgniter\Model->__call('where', [...])
 4 APPPATH\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('fdfd')
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:40:13 --> CodeIgniter\Database\Exceptions\DatabaseException: You must set the database table to be used with your query.
in SYSTEMPATH\Database\BaseConnection.php on line 884.
 1 SYSTEMPATH\Model.php(663): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH\Model.php(869): CodeIgniter\Model->builder()
 3 APPPATH\Models\login\loginModel.php(11): CodeIgniter\Model->__call('where', [...])
 4 APPPATH\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('fgdf')
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:41:14 --> CodeIgniter\Database\Exceptions\DatabaseException: You must set the database table to be used with your query.
in SYSTEMPATH\Database\BaseConnection.php on line 884.
 1 SYSTEMPATH\Model.php(663): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH\Model.php(869): CodeIgniter\Model->builder()
 3 APPPATH\Models\login\loginModel.php(11): CodeIgniter\Model->__call('where', [...])
 4 APPPATH\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('sasa')
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:41:53 --> CodeIgniter\Database\Exceptions\DatabaseException: You must set the database table to be used with your query.
in SYSTEMPATH\Database\BaseConnection.php on line 884.
 1 SYSTEMPATH\Model.php(663): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH\Model.php(869): CodeIgniter\Model->builder()
 3 APPPATH\Models\login\loginModel.php(11): CodeIgniter\Model->__call('where', [...])
 4 APPPATH\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('wewe')
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 02:42:37 --> CodeIgniter\Database\Exceptions\DatabaseException: You must set the database table to be used with your query.
in SYSTEMPATH\Database\BaseConnection.php on line 884.
 1 SYSTEMPATH\Model.php(663): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH\Model.php(869): CodeIgniter\Model->builder()
 3 APPPATH\Models\login\loginModel.php(12): CodeIgniter\Model->__call('where', [...])
 4 APPPATH\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('wewe')
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 02:43:22 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\laragon\www\App_transports\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\App_transports\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\laragon\www\App_transports\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\App_transports\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\App_transports\app\Models\login\loginModel.php(14): CodeIgniter\Database\BaseConnection->query('SELECT 1')
#4 C:\laragon\www\App_transports\app\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('sasas')
#5 C:\laragon\www\App_transports\system\CodeIgniter.php(943): App\Controllers\login\login->login()
#6 C:\laragon\www\App_transports\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
#7 C:\laragon\www\App_transports\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\App_transports\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\laragon\www\App_transports\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\App_transports\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\App_transports\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\App_transports\app\Models\login\loginModel.php(14): CodeIgniter\Database\BaseConnection->query('SELECT 1')
#3 C:\laragon\www\App_transports\app\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('sasas')
#4 C:\laragon\www\App_transports\system\CodeIgniter.php(943): App\Controllers\login\login->login()
#5 C:\laragon\www\App_transports\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
#6 C:\laragon\www\App_transports\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\App_transports\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-04-03 02:43:22 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\login\loginModel.php(14): CodeIgniter\Database\BaseConnection->query('SELECT 1')
 3 APPPATH\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('sasas')
 4 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 5 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 02:43:45 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\laragon\www\App_transports\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\App_transports\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\laragon\www\App_transports\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\App_transports\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\App_transports\app\Models\login\loginModel.php(14): CodeIgniter\Database\BaseConnection->query('SELECT 1')
#4 C:\laragon\www\App_transports\app\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('sasas')
#5 C:\laragon\www\App_transports\system\CodeIgniter.php(943): App\Controllers\login\login->login()
#6 C:\laragon\www\App_transports\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
#7 C:\laragon\www\App_transports\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\App_transports\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\laragon\www\App_transports\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\App_transports\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\App_transports\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\App_transports\app\Models\login\loginModel.php(14): CodeIgniter\Database\BaseConnection->query('SELECT 1')
#3 C:\laragon\www\App_transports\app\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('sasas')
#4 C:\laragon\www\App_transports\system\CodeIgniter.php(943): App\Controllers\login\login->login()
#5 C:\laragon\www\App_transports\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
#6 C:\laragon\www\App_transports\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\App_transports\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-04-03 02:43:45 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\login\loginModel.php(14): CodeIgniter\Database\BaseConnection->query('SELECT 1')
 3 APPPATH\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('sasas')
 4 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 5 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 02:43:45 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\laragon\www\App_transports\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\App_transports\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\laragon\www\App_transports\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\App_transports\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\App_transports\app\Models\login\loginModel.php(14): CodeIgniter\Database\BaseConnection->query('SELECT 1')
#4 C:\laragon\www\App_transports\app\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('sasas')
#5 C:\laragon\www\App_transports\system\CodeIgniter.php(943): App\Controllers\login\login->login()
#6 C:\laragon\www\App_transports\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
#7 C:\laragon\www\App_transports\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\App_transports\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\laragon\www\App_transports\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\App_transports\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\App_transports\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\App_transports\app\Models\login\loginModel.php(14): CodeIgniter\Database\BaseConnection->query('SELECT 1')
#3 C:\laragon\www\App_transports\app\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('sasas')
#4 C:\laragon\www\App_transports\system\CodeIgniter.php(943): App\Controllers\login\login->login()
#5 C:\laragon\www\App_transports\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
#6 C:\laragon\www\App_transports\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\App_transports\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-04-03 02:43:45 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\login\loginModel.php(14): CodeIgniter\Database\BaseConnection->query('SELECT 1')
 3 APPPATH\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('sasas')
 4 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 5 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 02:44:40 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\laragon\www\App_transports\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\App_transports\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\laragon\www\App_transports\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\App_transports\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\App_transports\app\Models\login\loginModel.php(11): CodeIgniter\Database\BaseConnection->query('SELECT 1')
#4 C:\laragon\www\App_transports\app\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('sasas')
#5 C:\laragon\www\App_transports\system\CodeIgniter.php(943): App\Controllers\login\login->login()
#6 C:\laragon\www\App_transports\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
#7 C:\laragon\www\App_transports\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\App_transports\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\laragon\www\App_transports\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\App_transports\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\App_transports\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\App_transports\app\Models\login\loginModel.php(11): CodeIgniter\Database\BaseConnection->query('SELECT 1')
#3 C:\laragon\www\App_transports\app\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('sasas')
#4 C:\laragon\www\App_transports\system\CodeIgniter.php(943): App\Controllers\login\login->login()
#5 C:\laragon\www\App_transports\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
#6 C:\laragon\www\App_transports\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\App_transports\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-04-03 02:44:40 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\login\loginModel.php(11): CodeIgniter\Database\BaseConnection->query('SELECT 1')
 3 APPPATH\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('sasas')
 4 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 5 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 02:46:53 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\laragon\www\App_transports\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\App_transports\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\laragon\www\App_transports\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\App_transports\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\App_transports\app\Models\login\loginModel.php(15): CodeIgniter\Database\BaseConnection->query('SELECT 1')
#4 C:\laragon\www\App_transports\app\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('dsds')
#5 C:\laragon\www\App_transports\system\CodeIgniter.php(943): App\Controllers\login\login->login()
#6 C:\laragon\www\App_transports\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
#7 C:\laragon\www\App_transports\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\App_transports\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\laragon\www\App_transports\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\App_transports\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\App_transports\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\App_transports\app\Models\login\loginModel.php(15): CodeIgniter\Database\BaseConnection->query('SELECT 1')
#3 C:\laragon\www\App_transports\app\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('dsds')
#4 C:\laragon\www\App_transports\system\CodeIgniter.php(943): App\Controllers\login\login->login()
#5 C:\laragon\www\App_transports\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
#6 C:\laragon\www\App_transports\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\App_transports\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-04-03 02:46:53 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\login\loginModel.php(15): CodeIgniter\Database\BaseConnection->query('SELECT 1')
 3 APPPATH\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('dsds')
 4 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 5 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 02:54:29 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\laragon\www\App_transports\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\App_transports\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\laragon\www\App_transports\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\App_transports\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\App_transports\app\Models\login\loginModel.php(15): CodeIgniter\Database\BaseConnection->query('SELECT 1')
#4 C:\laragon\www\App_transports\app\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('sasasa')
#5 C:\laragon\www\App_transports\system\CodeIgniter.php(943): App\Controllers\login\login->login()
#6 C:\laragon\www\App_transports\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
#7 C:\laragon\www\App_transports\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\App_transports\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\laragon\www\App_transports\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\App_transports\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\App_transports\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\App_transports\app\Models\login\loginModel.php(15): CodeIgniter\Database\BaseConnection->query('SELECT 1')
#3 C:\laragon\www\App_transports\app\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('sasasa')
#4 C:\laragon\www\App_transports\system\CodeIgniter.php(943): App\Controllers\login\login->login()
#5 C:\laragon\www\App_transports\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
#6 C:\laragon\www\App_transports\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\App_transports\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-04-03 02:54:29 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\login\loginModel.php(15): CodeIgniter\Database\BaseConnection->query('SELECT 1')
 3 APPPATH\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('sasasa')
 4 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 5 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 03:10:37 --> CodeIgniter\Database\Exceptions\DatabaseException: You must set the database table to be used with your query.
in SYSTEMPATH\Database\BaseConnection.php on line 884.
 1 SYSTEMPATH\Model.php(663): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH\Model.php(869): CodeIgniter\Model->builder()
 3 APPPATH\Models\login\loginModel.php(11): CodeIgniter\Model->__call('where', [...])
 4 APPPATH\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('asasa')
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 03:11:18 --> CodeIgniter\Database\Exceptions\DatabaseException: You must set the database table to be used with your query.
in SYSTEMPATH\Database\BaseConnection.php on line 884.
 1 SYSTEMPATH\Model.php(663): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH\Model.php(869): CodeIgniter\Model->builder()
 3 APPPATH\Models\login\loginModel.php(11): CodeIgniter\Model->__call('where', [...])
 4 APPPATH\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('asasa')
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 03:13:48 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM usuarios a WHERE a.usuario = 'asasa'' at line 1 in C:\laragon\www\App_transports\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\App_transports\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT FROM usu...', 0)
#1 C:\laragon\www\App_transports\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT FROM usu...')
#2 C:\laragon\www\App_transports\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT FROM usu...')
#3 C:\laragon\www\App_transports\app\Models\login\loginModel.php(11): CodeIgniter\Database\BaseConnection->query('SELECT FROM usu...', Array)
#4 C:\laragon\www\App_transports\app\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('asasa')
#5 C:\laragon\www\App_transports\system\CodeIgniter.php(943): App\Controllers\login\login->login()
#6 C:\laragon\www\App_transports\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
#7 C:\laragon\www\App_transports\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\App_transports\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-04-03 03:13:48 --> CodeIgniter\Database\Exceptions\DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM usuarios a WHERE a.usuario = 'asasa'' at line 1
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\login\loginModel.php(11): CodeIgniter\Database\BaseConnection->query('SELECT FROM usuarios a WHERE a.usuario = ?', [...])
 2 APPPATH\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('asasa')
 3 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 4 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 03:13:48 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM usuarios a WHERE a.usuario = 'asasa'' at line 1
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT FROM usuarios a WHERE a.usuario = \'asasa\'')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT FROM usuarios a WHERE a.usuario = \'asasa\'')
 3 APPPATH\Models\login\loginModel.php(11): CodeIgniter\Database\BaseConnection->query('SELECT FROM usuarios a WHERE a.usuario = ?', [...])
 4 APPPATH\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('asasa')
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 03:13:48 --> [Caused by] mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM usuarios a WHERE a.usuario = 'asasa'' at line 1
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT FROM usuarios a WHERE a.usuario = \'asasa\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT FROM usuarios a WHERE a.usuario = \'asasa\'')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT FROM usuarios a WHERE a.usuario = \'asasa\'')
 4 APPPATH\Models\login\loginModel.php(11): CodeIgniter\Database\BaseConnection->query('SELECT FROM usuarios a WHERE a.usuario = ?', [...])
 5 APPPATH\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('asasa')
 6 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 7 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 03:13:52 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM usuarios a WHERE a.usuario = 'asasa'' at line 1 in C:\laragon\www\App_transports\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\App_transports\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT FROM usu...', 0)
#1 C:\laragon\www\App_transports\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT FROM usu...')
#2 C:\laragon\www\App_transports\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT FROM usu...')
#3 C:\laragon\www\App_transports\app\Models\login\loginModel.php(11): CodeIgniter\Database\BaseConnection->query('SELECT FROM usu...', Array)
#4 C:\laragon\www\App_transports\app\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('asasa')
#5 C:\laragon\www\App_transports\system\CodeIgniter.php(943): App\Controllers\login\login->login()
#6 C:\laragon\www\App_transports\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
#7 C:\laragon\www\App_transports\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\App_transports\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-04-03 03:13:52 --> CodeIgniter\Database\Exceptions\DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM usuarios a WHERE a.usuario = 'asasa'' at line 1
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\login\loginModel.php(11): CodeIgniter\Database\BaseConnection->query('SELECT FROM usuarios a WHERE a.usuario = ?', [...])
 2 APPPATH\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('asasa')
 3 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 4 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 03:13:52 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM usuarios a WHERE a.usuario = 'asasa'' at line 1
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT FROM usuarios a WHERE a.usuario = \'asasa\'')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT FROM usuarios a WHERE a.usuario = \'asasa\'')
 3 APPPATH\Models\login\loginModel.php(11): CodeIgniter\Database\BaseConnection->query('SELECT FROM usuarios a WHERE a.usuario = ?', [...])
 4 APPPATH\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('asasa')
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 03:13:52 --> [Caused by] mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM usuarios a WHERE a.usuario = 'asasa'' at line 1
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT FROM usuarios a WHERE a.usuario = \'asasa\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT FROM usuarios a WHERE a.usuario = \'asasa\'')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT FROM usuarios a WHERE a.usuario = \'asasa\'')
 4 APPPATH\Models\login\loginModel.php(11): CodeIgniter\Database\BaseConnection->query('SELECT FROM usuarios a WHERE a.usuario = ?', [...])
 5 APPPATH\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('asasa')
 6 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 7 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-03 03:13:58 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM usuarios a WHERE a.usuario = 'sdsds'' at line 1 in C:\laragon\www\App_transports\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\App_transports\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT FROM usu...', 0)
#1 C:\laragon\www\App_transports\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT FROM usu...')
#2 C:\laragon\www\App_transports\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT FROM usu...')
#3 C:\laragon\www\App_transports\app\Models\login\loginModel.php(11): CodeIgniter\Database\BaseConnection->query('SELECT FROM usu...', Array)
#4 C:\laragon\www\App_transports\app\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('sdsds')
#5 C:\laragon\www\App_transports\system\CodeIgniter.php(943): App\Controllers\login\login->login()
#6 C:\laragon\www\App_transports\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
#7 C:\laragon\www\App_transports\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\App_transports\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-04-03 03:13:58 --> CodeIgniter\Database\Exceptions\DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM usuarios a WHERE a.usuario = 'sdsds'' at line 1
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\login\loginModel.php(11): CodeIgniter\Database\BaseConnection->query('SELECT FROM usuarios a WHERE a.usuario = ?', [...])
 2 APPPATH\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('sdsds')
 3 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 4 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 03:13:58 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM usuarios a WHERE a.usuario = 'sdsds'' at line 1
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT FROM usuarios a WHERE a.usuario = \'sdsds\'')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT FROM usuarios a WHERE a.usuario = \'sdsds\'')
 3 APPPATH\Models\login\loginModel.php(11): CodeIgniter\Database\BaseConnection->query('SELECT FROM usuarios a WHERE a.usuario = ?', [...])
 4 APPPATH\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('sdsds')
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 03:13:58 --> [Caused by] mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM usuarios a WHERE a.usuario = 'sdsds'' at line 1
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT FROM usuarios a WHERE a.usuario = \'sdsds\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT FROM usuarios a WHERE a.usuario = \'sdsds\'')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT FROM usuarios a WHERE a.usuario = \'sdsds\'')
 4 APPPATH\Models\login\loginModel.php(11): CodeIgniter\Database\BaseConnection->query('SELECT FROM usuarios a WHERE a.usuario = ?', [...])
 5 APPPATH\Controllers\login\login.php(44): App\Models\login\loginModel->get_data_user('sdsds')
 6 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 7 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 03:16:38 --> ErrorException: Undefined array key "password"
in APPPATH\Controllers\login\login.php on line 51.
 1 APPPATH\Controllers\login\login.php(51): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "password"', 'C:\\laragon\\www\\App_transports\\app\\Controllers\\login\\login.php', 51)
 2 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 3 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-03 03:17:58 --> ErrorException: Undefined array key "password"
in APPPATH\Controllers\login\login.php on line 52.
 1 APPPATH\Controllers\login\login.php(52): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "password"', 'C:\\laragon\\www\\App_transports\\app\\Controllers\\login\\login.php', 52)
 2 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\login\login->login()
 3 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login\login))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
